### ISSUE TITLE
WPS namelist generator leaves empty strings

### ISSUE THREAD

**Issue by HathewayWill** [JiriRichter/WRFDomainWizard#38] opened 2024-08-08 09:43 UTC
**Describe the bug**
the geog_data_res leaves strings empty when creating namelist.  should default to the 'default' settings

![image](https://github.com/user-attachments/assets/4a3c041b-f4f6-487e-80af-3466093a5dfc)

![image](https://github.com/user-attachments/assets/1c0be0ec-6dd6-41b3-886e-bc88880cf2af)

**Comment by JiriRichter** [comment] 2024-08-08 14:49
@HathewayWill , I am unable to reproduce this issue. Can you please provide more details?

**Comment by HathewayWill** [comment] 2024-08-08 18:26
Seems to be fixed, maybe it was a bug in the website?

**Comment by JiriRichter** [comment] 2024-08-08 18:44
I have deployed the latest version to the official location this morning so maybe this was something that got fixed along the way. I will resolve this as 'won't fix'. Feel free to reactivate this bug if you see it happening again.

**Closed by JiriRichter** 2024-08-08 18:44 UTC
Labels: bug

**Comment by HathewayWill** [comment] 2024-08-09 08:19
reopening issue:

It's when you hit the update button it resets the default geog option.  see video

[Screencast from 08-09-2024 03:18:09 AM.webm](https://github.com/user-attachments/assets/fcdb35ab-b967-4f77-95cc-14bef829ddc5)

**Comment by JiriRichter** [comment] 2024-08-09 16:40
I can repro.
